CREATE TABLE IF NOT EXISTS vehicle_photos (
  id UUID PRIMARY KEY NOT NULL,
  vehicle_id UUID NOT NULL
    CONSTRAINT fk_vehicle_id REFERENCES vehicles (id) ON UPDATE CASCADE ON DELETE CASCADE,
  asset_id UUID NOT NULL
    CONSTRAINT fk_asset_id REFERENCES assets (id) ON UPDATE CASCADE ON DELETE CASCADE,
  deleted BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS vehicle_license_photos (
  id UUID PRIMARY KEY NOT NULL,
  vehicle_id UUID NOT NULL
    CONSTRAINT fk_vehicle_id REFERENCES vehicles (id) ON UPDATE CASCADE ON DELETE CASCADE,
  asset_id UUID NOT NULL
    CONSTRAINT fk_asset_id REFERENCES assets (id) ON UPDATE CASCADE ON DELETE CASCADE,
  deleted BOOLEAN NOT NULL DEFAULT false
);
